[package]
name = "baby-bottle-temperature-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-sdk-sns = "0.24.0"
log = "0.4.17"
rust_gpiozero = "0.2.1"
